<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-12 08:07:16
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_kelompok_kerja' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$hari_id = isset( $_GET['hari_id'] ) ? $_GET['hari_id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> 
Waktu kerja <i class="fa fa-caret-right fa-fw"></i> Kelompok kerja ' ;


if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit_jadwal_hari" :
			$validatepost = validate_wt_kelompok_kerja_detail( );
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .=edit_wt_kelompok_kerja_detail($hari_id , $id); 
			}else{
				submit_wt_kelompok_kerja_detail();
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com'].'&task=detail_rincian_hari&id='.$id);
			 }
		
		break;
		case   "edit" :
			$validatepost = form_wt_kelompok_kerja_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_kelompok_kerja($id); 
			}else{
				submit_wt_kelompok_kerja($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com']);
			 }
		break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_wt_kelompok_kerja($id) ;
	}elseif($task == "edit_jadwal_hari"){ 
		$content =  edit_wt_kelompok_kerja_detail($hari_id , $id) ;
	}elseif($task == "detail_rincian_hari"){ 
		$content = detail_rincian_hari($id);
	}elseif($task == "delete"){ 
		my_delete_record('wt_kelompok_kerja','id', $id);
		my_direct("index.php?com=".$GET['com']);	
	}else{ 
		load_facebox_script();
		$content =  list_wt_kelompok_kerja() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
