<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 19:33:31
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('xl_builder' , false); 
my_component_load('pay_formula' , false);  
my_component_load('report_pay_pajak' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$karyawan_id = isset( $_GET['karyawan_id'] ) ? $_GET['karyawan_id']:  0;
$periode_id = isset( $_GET['periode_id'] ) ? $_GET['periode_id']:  0;
$modulname = 'Laporan <i class="fa fa-caret-right fa-fw"></i> 
		Reguler <i class="fa fa-caret-right fa-fw"></i> Perhitungan pajak ';

if($task == "cetak_masal"){
	ini_set("max_execution_time","10000"); 
	$nik_start = isset($_GET['nik_start']) ?  $_GET['nik_start']: '';
	$nik_end = isset($_GET['nik_end']) ? $_GET['nik_end'] : '';
	echo cetak_masal($nik_start ,$nik_end , $periode_id);
	exit;
}elseif($task == "detail_karyawan"){ 
	$content = list_pajak_by_karyawan($karyawan_id , $periode_id);
}elseif($task == "print_per_karyawan"){ 
	echo laporan_pajak_karyawan($karyawan_id , $periode_id);
	exit;
}elseif($task == "excel"){ 
	header("Content-Type: application/xls");
	$periode = my_get_data_by_id('pay_periode_reguler' , 'pay_periode_reguler_id', $periode_id );
	header("Content-Disposition: attachment;filename=pajak_{$periode['payroll_date']}_excel_all_".date('Ymd_His').".xls");
	echo excel_pajak_download($periode_id );
	exit;
}else{
	$content =  list_karyawan_pajak_proses($periode_id);
}

generate_my_web($content, $modulname );	