<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-11 11:42:30
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_jadwal_karyawan' );


$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$hari_id = isset( $_GET['hari_id'] ) ? $_GET['hari_id']:  0;
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$karyawan_id = isset( $_GET['karyawan_id'] ) ? $_GET['karyawan_id']:  0;

$modulname = 'Waktu kerja <i class="fa fa-caret-right fa-fw"></i> 
	Jadwal karyawan  ';

if($_SERVER['REQUEST_METHOD'] == "POST" ){

	if($task == 'edit_jadwal_eksepsi_karyawan'){
		$validatepost = validatejadwal_eksepsi_karyawan( );
		if($validatepost){
			$errors = message_multi_error($validatepost);
			$content = $errors;
			$content .= edit_jadwal_eksepsi_karyawan($karyawan_id,$hari_id); 
		}else{
			submit_jadwal_eksepsi_karyawan($karyawan_id,$hari_id);
			$content =  "Updated";
			my_direct('index.php?com='.$_GET['com'].'&task=detail_jadwal_karyawan&karyawan_id='.$karyawan_id);
		 }
		
	}
	elseif($task == 'edit'){
		$validatepost = validate_edit_jadwal_karyawan( );
		if($validatepost){
			$errors = message_multi_error($validatepost);
			$content = $errors;
			$content .=  edit_jadwal_karyawan($karyawan_id); 
		}else{
			submit_edit_jadwal_karyawan($karyawan_id );
			$content =  "Updated";
			my_direct('index.php?com='.$_GET['com'] );
		 }
		
	}
	
}else{


	if($task == 'edit'){
		$content =  edit_jadwal_karyawan($karyawan_id); 
	
	}elseif($task == 'hapus_jadwal_eksepsi_karyawan'){
		$query = "DELETE FROM wt_jadwal_kerja_eksepsi 
			WHERE karyawan_id = {$karyawan_id} 
			AND hari_id = {$hari_id} LIMIT 1";  
		my_query($query);
		my_direct($_SERVER['HTTP_REFERER']);
	
	}elseif($task == 'edit_jadwal_eksepsi_karyawan'){
		$content = edit_jadwal_eksepsi_karyawan($karyawan_id,$hari_id);
	
	}elseif($task == 'detail_jadwal_karyawan'){
		$content =  detail_jadwal_karyawan($karyawan_id); 
	
	}else{
		$content =  list_jadwal_karyawan(); 
	
	}
}

generate_my_web($content, $modulname );