<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-21 20:23:03
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_periode_reguler' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;

$modulname = 'Proses gaji <i class="fa fa-caret-right fa-fw"></i> Reguler
	<i class="fa fa-caret-right fa-fw"></i> Setel periode' ;

if($_SERVER['REQUEST_METHOD'] == "POST" ): 
	$validatepost = form_pay_periode_reguler_validate($id);
	if($validatepost){
		$errors = message_multi_error($validatepost);
		$content = $errors;
	}else{
		$id = submit_pay_periode_reguler(0); 
		$content = message_correct("Proses setelan periode penggajian berhasil ");
		
	} 
	$content .= edit_pay_periode_reguler($id); 
else:   
	$id = (int) current_periode_id();
	$content =  edit_pay_periode_reguler($id) ;  
endif; 
generate_my_web($content, $modulname );
?> 