<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 10:15:53
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_komponen_gaji' );
if(! isset($_GET['type']) ){
	$_GET['type'] = 'pendapatan';
}
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Komponen <i class="fa fa-caret-right fa-fw"></i> '.ucfirst($_GET['type']);

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_pay_komponen_gaji_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_pay_komponen_gaji($id); 
			}else{
				submit_pay_komponen_gaji($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com'].'&type='.$_GET['type']);
			 }
			break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_pay_komponen_gaji($id) ;
	}elseif($task == "delete"){ 
		my_delete_record('pay_komponen_gaji','pay_komponen_gaji_id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content =  list_pay_komponen_gaji() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
