<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 19:33:31
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('xl_builder' , false); 
my_component_load('pay_formula' , false);  
my_component_load('report_unreg_slip_gaji' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$karyawan_id = isset( $_GET['karyawan_id'] ) ? $_GET['karyawan_id']:  0;
$periode_id = isset( $_GET['periode_id'] ) ? $_GET['periode_id']:  0;
$modulname = 'Laporan <i class="fa fa-caret-right fa-fw"></i> 
		Reguler <i class="fa fa-caret-right fa-fw"></i> Slip gaji ';

if($task == "cetak_masal"){
	ini_set("max_execution_time","10000"); 
	$nik_start = isset($_GET['nik_start']) ?  $_GET['nik_start']: '';
	$nik_end = isset($_GET['nik_end']) ? $_GET['nik_end'] : '';
	echo cetak_masal($nik_start ,$nik_end , $periode_id);
	exit;
}elseif($task == "print_per_karyawan"){ 
	echo print_per_karyawan($karyawan_id , $periode_id);
	exit;
}elseif($task == "excel"){ 
	header("Content-Type: application/xls");;
	header("Content-Disposition: attachment;filename=kalkulasi_excel_all_".date('Ymd_His').".xls");
	echo excel_slip_gaji_download($periode_id );
	exit;
}else{
	$content =  list_datas_karyawan($periode_id);
}

generate_my_web($content, $modulname );		