<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-06 20:42:00
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_tipe_cuti' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Waktu kerja 
<i class="fa fa-caret-right fa-fw"></i> Data jenis cuti';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_wt_tipe_cuti_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_tipe_cuti($id);
				generate_my_web($content,"","plain.php");
				exit; 
			}else{
				submit_wt_tipe_cuti($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com']);
			 }
			break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_wt_tipe_cuti($id) ;
	}elseif($task == "delete"){ 
		my_delete_record('wt_tipe_cuti','id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content =  list_wt_tipe_cuti() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
