<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-21 08:46:03
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_komponen_manual' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$komponen_id = isset( $_GET['komponen_id'] ) ? $_GET['komponen_id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Renumerasi 
<i class="fa fa-caret-right fa-fw"></i> Data komponen gaji manual ';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "upload" :
			$validatepost = form_pay_komponen_upload_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= komponen_upload($komponen_id); 
			}else{
				form_upload_proses($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com'].'&task=list_karyawan_by_komponen&komponen_id='.$komponen_id);
			 }
		break; 
		case   "edit" :
			$validatepost = form_pay_komponen_manual_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_pay_komponen_manual($id); 
			}else{
				submit_pay_komponen_manual($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com'].'&task=list_karyawan_by_komponen&komponen_id='.$komponen_id);
			  }
		break; 
	}
else: 	
	if($task == "upload"){
		$content = komponen_upload($komponen_id);
	}elseif($task == "edit"){ 
		$content =  edit_pay_komponen_manual($id,$komponen_id) ;
	}elseif($task == "delete"){ 
		my_delete_record('pay_komponen_manual','pay_komponen_manual_id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}elseif($task == 'list_karyawan_by_komponen'){  
		$content =  list_pay_komponen_manual($komponen_id) ; 
	}else{
		$content =  list_komponen();
	}
endif; 
generate_my_web($content, $modulname );
?>
