<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-06 21:21:22
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_overtime' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Data referensi 
<i class="fa fa-caret-right fa-fw"></i> Pelaksanaan lembur';


if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_wt_overtime_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_overtime($id); 
			}else{
				submit_wt_overtime($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com']);
			 }
			break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_wt_overtime($id) ;
	}elseif($task == "delete"){ 
		my_delete_record('wt_overtime','id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content = list_wt_overtime() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
