<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 19:33:31
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('xl_builder' , false); 
my_component_load('pay_formula' , false);  
my_component_load('report_pay_komponen' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$komponen_id = isset( $_GET['komponen_id'] ) ? $_GET['komponen_id']:  0;
$periode_id = isset( $_GET['periode_id'] ) ? $_GET['periode_id']:  0;
$modulname = 'Laporan <i class="fa fa-caret-right fa-fw"></i> 
		Reguler <i class="fa fa-caret-right fa-fw"></i> Data komponen &amp; item ';

if($task == "cetak_masal"){
	ini_set("max_execution_time","10000");  
	echo cetak_per_komponen($komponen_id , $periode_id);
	exit; 
}elseif($task == "detail_komponen"){ 
	$content = list_detail_karyawan_by_komponen($komponen_id , $periode_id);
	 
}elseif($task == "excel_per_komponen"){ 
	header("Content-Type: application/xls");
	$datas = get_komponen_detail( $komponen_id , $periode_id );
	header("Content-Disposition: attachment;filename=detail_komponen_".str_replace(" ","_",$datas['pay_komponen_gaji_name'])."_{$datas['pay_periode_date']}_excel_all_".date('Ymd_His').".xls");
	echo excel_komponen_detail($periode_id , $komponen_id );
	exit; 
}elseif($task == "excel"){ 
	header("Content-Type: application/xls");
	$periode = my_get_data_by_id('pay_periode_reguler' , 'pay_periode_reguler_id', $periode_id );
	header("Content-Disposition: attachment;filename=data_komponen_{$periode['payroll_date']}_excel_all_".date('Ymd_His').".xls");
	echo excel_komponen_all($periode_id );
	exit;
}else{
	$content =  list_komponen_hasil($periode_id);
}

generate_my_web($content, $modulname );	