<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-19 10:14:15
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('list_kalender' , false);  
my_component_load('progress_bar' ,false );
my_component_load('wt_periode' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Waktu kerja <i class="fa fa-caret-right fa-fw"></i> Penghitungan
<i class="fa fa-caret-right fa-fw"></i> Periode kerja';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_wt_periode_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_periode($id);
			}else{
				submit_wt_periode($id); 
				my_direct('index.php?com='.$_GET['com']);
			}
		break; 
	}
else: 	
	if($task == "detail"){ 
		if($id == 0)
			$content =  detail_list_kalendar_proses( );
		else
			$content =  detail_list_kalendar_proses( );
	}elseif($task == "kalkulasi"){ 
		ini_set("max_execution_time","10000");
		kalkulasi_waktu_kerja();
		echo '<center><h2>Selesai</h2>';
		echo '<a href="index.php?com='.$_GET['com'].'&task=detail&id=0">Kembali ke aplikasi</a></center>';
		exit;		
	}else{ 
		load_facebox_script();
		$content =  list_wt_periode() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
