<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 19:33:31
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_formula' , false);  
my_component_load('unreg_proses_pajak' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$karyawan_id = isset( $_GET['karyawan_id'] ) ? $_GET['karyawan_id']:  0;
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Proses gaji <i class="fa fa-caret-right fa-fw"></i> 
		Reguler <i class="fa fa-caret-right fa-fw"></i> Komponen hasil';

if($task == "detail"){
	$content = list_pajak_by_karyawan($karyawan_id); 
}else{
	$content = list_karyawan_pajak_proses();
}

generate_my_web($content, $modulname );		