<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-14 11:42:30
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_benefit_group' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$karyawan_gol_jab_id = isset( $_GET['karyawan_gol_jab_id'] ) ? $_GET['karyawan_gol_jab_id']:  0;
$pay_benefit_group_id = isset( $_GET['pay_benefit_group_id'] ) ? $_GET['pay_benefit_group_id']:  0;
if(! isset($_GET['type'])){
	$_GET['type'] = 'subsidi';
}
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Tarif dasar <i class="fa fa-caret-right fa-fw"></i> '.ucfirst($_GET['type']);

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_pay_benefit_group_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_pay_benefit_group($id); 
			}else{
				submit_pay_benefit_group($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com'].'&task=detail&type='.$_GET['type']);
			 }
		break;

		case "edit_nominal":
			$validatepost = false;//form_pay_benefit_group_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .=  edit_nominal_tarif($karyawan_gol_jab_id , $pay_benefit_group_id);
			}else{
				update_tarif($karyawan_gol_jab_id , $pay_benefit_group_id);
				my_direct('index.php?com='.$_GET['com'].'&type='.$_GET['type'].'&task=detail&id='.$pay_benefit_group_id);
			}
		break;
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_pay_benefit_group($id) ;
	}elseif($task == "edit_nominal"){   
		$content =  edit_nominal_tarif($karyawan_gol_jab_id , $pay_benefit_group_id);
	}elseif($task == "detail"){   
		$content =  detail_tarif($id);
	}elseif($task == "delete"){ 
		my_delete_record('pay_benefit_group','pay_benefit_group_id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		$content =  list_pay_benefit_group() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
