<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-15 19:33:31
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('xl_builder' , false); 
my_component_load('pay_formula' , false); 
my_component_load('progress_bar' ,false );
my_component_load('pay_proses_kalkulasi_reguler' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Proses gaji <i class="fa fa-caret-right fa-fw"></i> 
		Reguler <i class="fa fa-caret-right fa-fw"></i> Kalkulasi ';

if($task == "kalkulasi"){
	
	ini_set("max_execution_time","10000");
	proses_kalkulasi_all(); 
	echo '<center><h2>Selesai</h2>';
	echo '<a href="index.php?com='.$_GET['com'].'">Kembali ke aplikasi</a></center>';
	exit;
}elseif($task == "excel"){ 
	header("Content-Type: application/xls");;
	header("Content-Disposition: attachment;filename=kalkulasi_excel_all_".date('Ymd_His').".xls");
	echo excel_kalkulasi_download( );
	exit;
}else{
	$content = list_karyawan_kalkulasi();
}

generate_my_web($content, $modulname );		