<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-14 09:13:02
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_jurnal_gaji' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i> Data Referensi <i class="fa fa-caret-right fa-fw"></i> Jurnal penggajian ';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_pay_jurnal_gaji_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_pay_jurnal_gaji($id); 
			}else{
				submit_pay_jurnal_gaji($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com']);
			 }
			break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_pay_jurnal_gaji($id) ;
	}elseif($task == "delete"){ 
		my_delete_record('pay_jurnal_gaji','pay_jurnal_gaji_id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content =  list_pay_jurnal_gaji() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
