<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-14 10:03:33
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('karyawan_rekening' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$rekening_id = isset( $_GET['rekening_id'] ) ? $_GET['rekening_id']:  0;
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Karyawan <i class="fa fa-caret-right fa-fw"></i> 
	Rekening bank karyawan   ';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
	
	switch($task){
	case 'edit':
		$validates = form_karyawan_rekening_validate($id , $rekening_id);
		if($validates){
			$content = message_multi_error($validates);
			$content .=  edit_karyawan_rekening($id , $rekening_id) ;
		}else{
			save_rekening($id , $rekening_id);
			my_direct('index.php?com='.$_GET['com'].'&task=rekening&id='.$id);
		}
	break;
	
	case 'rekening':
		$validates = balance_100_rekening($id  );
		if($validates){
			$content = message_multi_error($validates);
		}else{ 
			balance_distribusi($id);
			$content = message_correct('Data persen distribusi di ubah');
		}
		$content .=  detail_rekening($id  ) ;
	break;
	}

else: 	
	if($task == "rekening"){ 
		$content =  detail_rekening($id) ;
	}elseif($task == "edit"){ 
		$content =  edit_karyawan_rekening($id , $rekening_id) ;
	
	}elseif($task == "delete"){ 
		$fields = my_get_data_by_id('karyawan_bank_account','rekening_id', $id);
		my_delete_record('karyawan_bank_account','rekening_id', $id);
		set_auto_portion($fields['karyawan_id']);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();  
		$content =  list_karyawan() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
