<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-21 20:23:03
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('pay_formula' , false); 
my_component_load('progress_bar' ,false );
my_component_load('unreg_proses_kalkulasi' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;

$modulname = 'Proses gaji <i class="fa fa-caret-right fa-fw"></i> Unreguler
	<i class="fa fa-caret-right fa-fw"></i> Hasil kalkulasi' ;
	 
if($task == 'kalkulasi'){
	ini_set("max_execution_time","10000");
	proses_hitung_kalkulasi(); 
	echo '<center><h2>Selesai</h2>';
	echo '<a href="index.php?com='.$_GET['com'].'">Kembali ke aplikasi</a></center>';
	exit;
}else{
	$content = list_karyawan_kalkulasi();
}

generate_my_web($content, $modulname );
?>