<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-08 21:04:53
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_implementasi_ijin' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$modulname = 'Waktu kerja <i class="fa fa-caret-right fa-fw"></i> Pelaksanaan ijin';

if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_wt_implementasi_ijin_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_implementasi_ijin($id); 
			}else{
				submit_wt_implementasi_ijin($id);
				$content =  "Updated";
				my_direct('index.php?com='.$_GET['com']);
			 }
			break; 
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_wt_implementasi_ijin($id) ;
	}elseif($task == "delete"){ 
		my_delete_record('wt_implementasi_ijin','wt_implementasi_ijin_id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content =  list_wt_implementasi_ijin() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
