<?php
/*
	Files generated by Kornea auto 
	On : 2015-03-21 20:23:03
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('unreg_set_param' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']: check_current_periode_unreg();

$modulname = 'Proses gaji <i class="fa fa-caret-right fa-fw"></i> Unreguler
	<i class="fa fa-caret-right fa-fw"></i> Setel parameter' ;
	
if($_SERVER['REQUEST_METHOD'] == "POST" ){	
 
	$validatepost = set_param_validate($id);
	if($validatepost){
		$errors = message_multi_error($validatepost);
		$content = $errors;
	}else{
		$id = set_param_submit($id); 
		$content = message_correct("Proses setelan periode penggajian unreguler berhasil ");	
	} 
	$content .= form_set_parameter($id); 
	 
}else{
	$content =  form_set_parameter($id) ;	
}
generate_my_web($content, $modulname );
?>	