<?php
/*
	Files generated by Kornea auto 
	On : 2015-09-11 20:39:16
*/	
my_component_load('__jsload' , false);
my_component_load('__paging' , false);  
my_component_load('wt_jadwal_kerja' );
$task = isset($_GET['task']) ? $_GET['task'] : ''; 
$id = isset( $_GET['id'] ) ? $_GET['id']:  0;
$hari_id = isset( $_GET['hari_id'] ) ? $_GET['hari_id']:  0;
$modulname = 'Konfigurasi <i class="fa fa-caret-right fa-fw"></i>
 Waktu kerja <i class="fa fa-caret-right fa-fw"></i> Data jadwal kerja';


if($_SERVER['REQUEST_METHOD'] == "POST" ):
 	switch($task){
		case   "edit" :
			$validatepost = form_wt_jadwal_kerja_validate($id);
			if($validatepost){
				$errors = message_multi_error($validatepost);
				$content = $errors;
				$content .= edit_wt_jadwal_kerja($id); 
			}else{
				submit_wt_jadwal_kerja($id); 
				my_direct('index.php?com='.$_GET['com']);
			 }
		break;  
	}
else: 	
	if($task == "edit"){ 
		$content =  edit_wt_jadwal_kerja($id) ;
	}elseif($task == "edit_jadwal_hari"){ 
		$content = edit_jam_jadwal_kerja($id , $hari_id);
	 
	}elseif($task == "delete"){ 
		my_delete_record('wt_jadwal_kerja','id', $id);
		my_direct($_SERVER['HTTP_REFERER']);	
	}else{ 
		load_facebox_script();
		$content =  list_wt_jadwal_kerja() ; 
	}
endif; 
generate_my_web($content, $modulname );
?>
